package org.example;

import java.util.List;

/**
 * Consumer that receives the terms of the geometric progression generated by producer and logs them as received.
 */
public class Consumer implements Runnable {

    private final WaitQueue<Long> buffer;
    private final int terms;
    private final List<Long> destination;

    public Consumer(WaitQueue<Long> buffer, int terms, List<Long> destination) {
        this.buffer = buffer;
        this.terms = terms;
        this.destination = destination;
    }

    @Override
    public void run() {
        try {
            for (int i = 0; i < terms; i++) {
                Long value = buffer.take(); //pulls the data from queue
                destination.add(value); // adds the terms into the destination array
                System.out.println((i + 1)+" th term in GP is : " + value);
            }
        } catch (InterruptedException e) { // Unexpected Exception
            Thread.currentThread().interrupt();
        }
    }
}